# Generated by Django 4.1.2 on 2022-10-09 11:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OriginalUrl",
            fields=[
                (
                    "original_url_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_url", models.CharField(max_length=500)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 10, 9, 11, 57, 8, 403705),
                        null=True,
                    ),
                ),
            ],
        ),
    ]
