# Generated by Django 4.1.2 on 2022-10-10 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OriginalUrl",
            fields=[
                (
                    "original_url_id",
                    models.CharField(
                        default="nbwz", max_length=5, primary_key=True, serialize=False
                    ),
                ),
                ("original_url", models.CharField(max_length=500)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
            ],
        ),
    ]
