# Generated by Django 4.1.2 on 2022-10-10 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OriginalUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url_id", models.CharField(max_length=10, unique=True)),
                ("original_url", models.CharField(max_length=500, unique=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
            ],
        ),
    ]
