# Generated by Django 4.1.2 on 2022-10-09 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortening_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="originalurl",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 9, 11, 59, 12, 360608, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
