# Generated by Django 4.1.2 on 2022-10-09 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("url_shortening_app", "0002_alter_originalurl_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="originalurl",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
